### ISSUE TITLE
api.search gives lots of tiles that did not 

### ISSUE THREAD

**Issue by tongqiugeog** [kapadia/usgs#45]
Hi,

I am using the following code to search Landsat ARD images in the Chapel Hill. 

`from usgs import api

results = api.search('ARD_TILE', 'EE', distance = 1, lat = 36.0132, lng = -79.032, start_date = '1999-01-01', end_date = '1999-12-31', max_results = 1000)

for scene in results['data']['results']:
    print scene['entityId']
`
However, the api gives me many tiles that did not belong to the Chapel Hill region. (I set the maximum to be 1000). I use the same criteria on earthexplorer, it gives me 54 results. 

The results of the code is attached. 

Best,
Tong
[out.txt](https://github.com/kapadia/usgs/files/2498481/out.txt)

**Comment by kapadia** [comment]
@tongqiugeog It looks like the spatial search broke when we recently updated to a newer versioned API from USGS. I've updated the query parameters so that spatial searches work correctly again. I've also added a `--max-results` CLI parameter so that you can test from the command line:

```
usgs search --node EE ARD_TILE --distance 1 --latitude 36.0132 --longitude -79.032 --start-date 1999-01-01 --end-date 1999-12-31 --max-results 1000
```

Just `pip install usgs --upgrade` to get the updated version of this library. Thanks for the bug report.
