### ISSUE TITLE
USGS API  1.4 deprecated in March 2021

### ISSUE THREAD

**Issue by maximlt** [kapadia/usgs#51]
Hi!

The [USGS has announced](https://earthexplorer.usgs.gov/inventory/documentation/json-api) that the version of the API used by this package (1.4.0) would be deprecated on March 17, 2021. They recommend upgrading to version 1.5, which is their *Machine-to-Machine API*.

Is this upgrade also planned for this package?

Thanks a lot!

**Comment by kapadia** [comment]
@maximlt thanks for raising this issue. This library is used to support the [Landsat on AWS](https://registry.opendata.aws/landsat-8/) project, which is still in operation. I'll get it updated so that data stream continues to operate. Thanks for the link to the documentation as well, I had searched for it a few months back and was unable to find it.

**Comment by kapadia** [comment]
https://github.com/kapadia/usgs/pull/52 addresses the deprecated API. The most recent version is now on PyPI. Unfortunately these updates are not backwards compatible.
